export { notificationsAPI } from "./api/notificationsAPI";
export { productsAPI } from "./api/productsAPI";
export { categoriesAPI } from "./api/categoriesAPI";
export { suppliersAPI } from "./api/suppliersAPI";
export { customersAPI } from "./api/customersAPI";
export { salesAPI } from "./api/salesAPI";
export { employeesAPI } from "./api/employeesAPI";
export { reportsAPI } from "./api/reportsAPI";
export { inventoryAPI } from "./api/inventoryAPI";
export { parkedSalesAPI } from "./api/parkedSalesAPI";
export { quickSaleItemsAPI } from "./api/quickSaleItemsAPI";
export { loyaltyAPI } from "./api/loyaltyAPI";
export { analyticsAPI } from "./api/analyticsAPI";
export { receiptsAPI } from "./api/receiptsAPI";
export { returnsAPI } from "./api/returnsAPI";
export { posSettingsAPI } from "./api/posSettingsAPI";
export { cashDrawerAPI } from "./api/cashDrawerAPI";
export { authAPI } from "./api/authAPI";
// Add more API exports here as you split them
